from logging import getLevelName
from os import getenv

from constants import (
    DEFAULT_DATASET,
    DEFAULT_DATASET_FOLDER,
    DEFAULT_EPOCHS,
    DEFAULT_LOGGING_LEVEL,
    DEFAULT_MASTER_ADDR,
    DEFAULT_MASTER_PORT,
    DEFAULT_NEURAL_NETWORK,
    DEFAULT_NUM_NODES,
    DEFAULT_OUTPUT,
    DEFAULT_TRAINING,
    DEFAULT_VERBOSE,
    DEFAULT_WORKERS_PER_NODE,
    UNDEFINED_NODE_ID,
)

NODE_ID = getenv("NODE_ID") or UNDEFINED_NODE_ID
NUM_NODES = getenv("NUM_NODES") or f"{DEFAULT_NUM_NODES}"
WORKERS_PER_NODE = getenv("WORKERS_PER_NODE") or f"{DEFAULT_WORKERS_PER_NODE}"

DATASET = getenv("DATASET") or DEFAULT_DATASET
NEURAL_NETWORK = getenv("NEURAL_NETWORK") or DEFAULT_NEURAL_NETWORK
TRAINING = getenv("TRAINING") or DEFAULT_TRAINING

EPOCHS = getenv("EPOCHS") or f"{DEFAULT_EPOCHS}"

VERBOSE = getenv("VERBOSE") or f"{DEFAULT_VERBOSE}"
LOGGING_LEVEL = getenv("LOGGING_LEVEL") or getLevelName(DEFAULT_LOGGING_LEVEL)

DATASET_FOLDER = getenv("DATASET_FOLDER") or DEFAULT_DATASET_FOLDER
OUTPUT = getenv("OUTPUT") or DEFAULT_OUTPUT

MASTER_ADDR = getenv("MASTER_ADDR") or DEFAULT_MASTER_ADDR
MASTER_PORT = getenv("MASTER_PORT") or DEFAULT_MASTER_PORT
